name: fit_chauzar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^5.3.0
  flutter: 
    sdk: flutter
  webview_flutter: ^2.0.12
  flutter_screenutil: ^5.8.4
    

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
 

flutter: 
  uses-material-design: true

